version: 2.1
orbs:
  path-filtering: circleci/path-filtering@0.1.3

# This allows you to use CircleCI's dynamic configuration feature
setup: true

workflows:
  run-filter:
    jobs:
      - path-filtering/filter:
          # Compare files on main
          base-revision: main
          # 3-column space-separated table for mapping; `path-to-test parameter-to-set value-for-parameter` for each row
          mapping: |
            tests/legacy-cli/e2e/ng-snapshot/package.json snapshot_changed true
          config-path: '.circleci/dynamic_config.yml'
